# Generated by Django 4.2.7 on 2025-11-23 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commission',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='father_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='father_occupation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mother_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mother_occupation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='preferred_locations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='university',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='followup',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='leadsource',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='refund',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='permanent_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='registration',
            name='preferences',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='template',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='template_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='visatracking',
            name='company_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='candidate_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='variables',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='university',
            name='programs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='university',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEV_ADMIN', 'Dev Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='visatracking',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DELETE', 'Delete'), ('UPDATE', 'Update')], max_length=10)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('entity_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('company_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('pending_changes', models.JSONField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
