# Generated by Django 6.0.7 on 2026-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refund",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Processed", "Processed"),
                    ("Rejected", "Rejected"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
            ),
        ),
    ]
