# Generated by Django 6.0.7 on 2026-07-30 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_refund_status_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_company_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "document_number",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Received", "Received"),
                            ("With staff", "With staff"),
                            ("Submitted", "Submitted to university/embassy"),
                            ("Returned", "Returned to student"),
                            ("Lost", "Lost"),
                        ],
                        db_index=True,
                        default="Received",
                        max_length=20,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="core.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_holder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who physically holds this document right now.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="held_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current custodian. Changes when the record is transferred.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_documents",
                        to="core.registration",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["company", "branch"],
                        name="core_studen_company_aca7e3_idx",
                    ),
                    models.Index(
                        fields=["owner"], name="core_studen_owner_i_aade34_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="core_studen_created_fae603_idx"
                    ),
                    models.Index(
                        fields=["registration", "status"],
                        name="core_studen_registr_544494_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_company_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remark", models.TextField()),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="core.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current custodian. Changes when the record is transferred.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remarks",
                        to="core.registration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_remarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["company", "branch"],
                        name="core_studen_company_02b65b_idx",
                    ),
                    models.Index(
                        fields=["owner"], name="core_studen_owner_i_873b38_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="core_studen_created_d685d7_idx"
                    ),
                ],
            },
        ),
    ]
