# Generated by Django 6.0.7 on 2026-07-30 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_student_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="admission_possibility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("High", "High"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                    ("Unknown", "Unknown"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="followup",
            name="outcome_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Not reached", "Could not reach"),
                    ("Interested", "Interested"),
                    ("Thinking", "Still deciding"),
                    ("Not interested", "Not interested"),
                    ("Converted", "Converted"),
                ],
                db_index=True,
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="FollowUpComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_company_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_up_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)ss",
                        to="core.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "follow_up",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.followup",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current custodian. Changes when the record is transferred.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["company", "branch"],
                        name="core_follow_company_f6d402_idx",
                    ),
                    models.Index(
                        fields=["owner"], name="core_follow_owner_i_58adce_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="core_follow_created_379c3a_idx"
                    ),
                ],
            },
        ),
    ]
