# Generated by Django 6.0.7 on 2026-07-31 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_registration_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DEV_ADMIN", "Dev Admin"),
                            ("COMPANY_ADMIN", "Company Admin"),
                            ("HEAD_MANAGER", "Head Manager"),
                            ("BRANCH_MANAGER", "Branch Manager"),
                            ("EMPLOYEE", "Employee"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("manageCompanies", "Manage companies"),
                            ("manageBranches", "Manage branches"),
                            ("manageUsers", "Manage staff accounts"),
                            ("viewAnalytics", "View analytics"),
                            ("viewEarnings", "View earnings and commissions"),
                            ("manageCommissions", "Manage commissions and agents"),
                            (
                                "manageSettings",
                                "Manage company settings and permissions",
                            ),
                            ("reviewApprovals", "Review approval requests"),
                            ("manageCounselors", "View counselor performance"),
                            ("manageLeadSources", "Manage lead sources"),
                            ("manageRefunds", "File and approve refunds"),
                            ("deleteRecords", "Delete records directly"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "allowed",
                    models.BooleanField(
                        help_text="Explicit grant or denial. Delete the row to return to the default."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="core.company",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_permission_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["company_id", "role", "capability"],
                "indexes": [
                    models.Index(
                        fields=["company", "role"],
                        name="core_rolepe_company_ae21e6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "role", "capability"),
                        name="uniq_role_permission_per_company",
                    )
                ],
            },
        ),
    ]
