# Generated by Django 6.0.7 on 2026-08-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_role_permission"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="leadsource",
            name="core_leadso_company_c0a0ce_idx",
        ),
        migrations.RemoveIndex(
            model_name="leadsource",
            name="core_leadso_owner_i_d322b8_idx",
        ),
        migrations.RemoveIndex(
            model_name="leadsource",
            name="core_leadso_created_b082cc_idx",
        ),
        migrations.RemoveConstraint(
            model_name="leadsource",
            name="uniq_leadsource_per_company",
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="capability",
            field=models.CharField(
                choices=[
                    ("manageCompanies", "Manage companies"),
                    ("manageBranches", "Manage branches"),
                    ("manageUsers", "Manage staff accounts"),
                    ("viewAnalytics", "View analytics"),
                    ("viewEarnings", "View earnings and commissions"),
                    ("manageCommissions", "Manage commissions and agents"),
                    ("manageSettings", "Manage company settings and permissions"),
                    ("reviewApprovals", "Review approval requests"),
                    ("manageCounselors", "View counselor performance"),
                    ("manageRefunds", "File and approve refunds"),
                    ("deleteRecords", "Delete records directly"),
                ],
                max_length=40,
            ),
        ),
        migrations.DeleteModel(
            name="LeadSource",
        ),
    ]
