# Generated by Django 6.0.7 on 2026-08-21 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_lead_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="enquiry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.enquiry",
            ),
        ),
    ]
